AllCops:
  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/LineContinuationSpacing:
  Enabled: true
  EnforcedStyle: space

Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: aligned